# Generated by Django 4.1 on 2025-01-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('client_app', '0028_scheduledfilemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot',
                 models.PositiveSmallIntegerField(choices=[(1, '脚本 1'), (2, '脚本 2'), (3, '脚本 3')], unique=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduledfilemessage',
            name='file_path',
            field=models.CharField(help_text='定时发送的文件路径，不需要带引号', max_length=1024),
        ),
    ]
