services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: tykWyr-bepqu6-fafvym
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  yuyuwechatv2_client:
    image: mona233/yuyuwechatv2_client:latest
    container_name: yuyuwechatv2_client
    ports:
      - "7500:7500"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tykWyr-bepqu6-fafvym
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CSRF_TRUSTED_ORIGINS=https://localhost,https://yourdomain.com  # 定义CSRF信任域
    volumes:
      - ./backups:/app/backups  # 挂载 ./backups 到容器的 /app/backups